In [2]:
print("hello")

hello


In [3]:
from sklearn import datasets

In [4]:
digits = datasets.load_digits()

In [11]:
digits.data[-1]

array([ 0.,  0., 10., 14.,  8.,  1.,  0.,  0.,  0.,  2., 16., 14.,  6.,
        1.,  0.,  0.,  0.,  0., 15., 15.,  8., 15.,  0.,  0.,  0.,  0.,
        5., 16., 16., 10.,  0.,  0.,  0.,  0., 12., 15., 15., 12.,  0.,
        0.,  0.,  4., 16.,  6.,  4., 16.,  6.,  0.,  0.,  8., 16., 10.,
        8., 16.,  8.,  0.,  0.,  1.,  8., 12., 14., 12.,  1.,  0.])

In [6]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [7]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100)

In [8]:
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100, gamma=0.001)

In [22]:
clf.predict((digits.data[-1]).reshape(1, -1))

array([8])